RUN apt-get update && apt-get install -y postgis postgresql-<versão>-postgis-3 --> instalar o postgis no container do postgres pois é necessario para item schema

exemplo postgres 16
RUN apt-get install -y postgis postgresql-16-postgis-3
https://postgis.net/documentation/getting_started/install_docker/